apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: si7t5z010-python 
  janus-idp.io/tekton: si7t5z010-python
  backstage.io/kubernetes-id: si7t5z010-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: si7t5z010-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml