apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: si7t5z010-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: si7t5z010-python 
  name: si7t5z010-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: si7t5z010-python
    weight: 100 
