apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: si7t5z010-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: si7t5z010-python 
  name: si7t5z010-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: si7t5z010-python 
